version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - yum install -y git   # Install Git
      - yum install -y wget  # Install wget to download Maven and JDK if not present
      - echo "Installing OpenJDK 17 from Amazon Corretto..."
      - wget https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.rpm  # Download Amazon Corretto OpenJDK 17
      - yum install -y amazon-corretto-17-x64-linux-jdk.rpm   # Install OpenJDK 17 from RPM
      - echo "Java version:"
      - java -version  # Check Java version
      - echo "Downloading Maven..."
      - wget https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz  # Corrected Maven download link
      - tar xzf apache-maven-3.8.8-bin.tar.gz -C /opt   # Extract Maven to /opt
      - ln -s /opt/apache-maven-3.8.8 /opt/maven   # Create symlink for easier access
      - export PATH=/opt/maven/bin:$PATH   # Add Maven to PATH
      - mvn -v  # Verify Maven installation
      - git --version  # Verify Git installation

  pre_build:
    commands:
      - echo "Setting up environment"
      - echo "Maven version:"
      - mvn -v  # Verify Maven version before build

  build:
    commands:
      - echo "Building the project"
      - mvn clean package  # Your actual build command
      - echo "Build successful"  # Success message

  post_build:
    commands:
      - echo "Deploying to EC2"
      - aws s3 cp target/mobilestore-0.0.1-SNAPSHOT.jar s3://mobilestore-artifacts/mobilestore-0.0.1-SNAPSHOT.jar  # Optionally, upload to S3 if needed
      - echo "Copying jar to EC2 instance"
      - scp -i s3://mobilestore-artifacts/app_jar/mobilestore.pem target/mobilestore-0.0.1-SNAPSHOT.jar ec2-user@44.211.74.58:/home/ec2-user/mobilestore-0.0.1-SNAPSHOT.jar
      - ssh -i s3://mobilestore-artifacts/app_jar/mobilestore.pem ec2-user@44.211.74.58 'java -jar /home/ec2-user/your-app.jar'  # Run the application on EC2
      
artifacts:
  files:
    - target/*.jar

