version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk17
      maven: 3.x
    commands:
      - echo "Installing dependencies"
      - yum install -y git
      - echo "Git version:"
      - git --version
  pre_build:
    commands:
      - echo "Setting up environment"
      - echo "Maven version:"
      - mvn -v
  build:
    commands:
      - echo "Building the project"
      - mvn clean package  # Replace the incorrect 'success' command with your build command
  post_build:
    commands:
      - echo "Build complete"
      - ls -l target/

artifacts:
  files:
    - target/*.jar
