version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk-17
    commands:
      # Install Maven if it's not available
      echo Installing Maven...
      curl -sSL https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz | tar -xz -C /usr/local
      export PATH=$PATH:/usr/local/apache-maven-3.8.4/bin
      # Verify the installation
      mvn -v

  pre_build:
    commands:
      # Setup your environment if needed
      echo Setting up environment variables...

  build:
    commands:
      # Build the Spring Boot application and package it as a .jar file
      echo Building the Spring Boot application...
      mvn clean package

  post_build:
    commands:
      # Deploy the application to a specific environment (if applicable)
      echo Build completed successfully

artifacts:
  files:
    - target/*.jar  # Output the jar file for further use (e.g., deployment)
  discard-paths: yes
  # Specify the S3 bucket and folder where the artifact should be uploaded
  base-directory: target  # Artifact directory in the build container
  name: mobilestore-0.0.1-SNAPSHOT.jar  # Optional: Name of the artifact file
  location: mobilestore-artifacts  # S3 Bucket name (Replace with your actual bucket name)
