version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk17   # Ensure you're using OpenJDK 17
    commands:
      - echo "Installing dependencies"
      - yum install -y git   # Install Git
      - yum install -y wget  # Install wget to download Maven
      - wget https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz  # Download Maven
      - tar xzf apache-maven-3.8.6-bin.tar.gz -C /opt   # Extract Maven to /opt
      - ln -s /opt/apache-maven-3.8.6 /opt/maven   # Create symlink for easier access
      - export PATH=/opt/maven/bin:$PATH   # Add Maven to PATH
      - mvn -v  # Verify Maven installation
      - git --version  # Verify Git installation

  pre_build:
    commands:
      - echo "Setting up environment"
      - echo "Maven version:"
      - mvn -v  # Verify Maven version again before build

  build:
    commands:
      - echo "Building the project"
      - mvn clean package  # Your actual build command
      - echo "Build successful"  # Success message

  post_build:
    commands:
      - echo "Build complete"
      - ls -l target/   # List the files in the target directory to check the output

artifacts:
  files:
    - target/*.jar   # Include JAR files in the artifacts
