version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk17
    commands:
      - echo "Installing dependencies"
      - yum install -y git
      - echo "Git version:"
      - git --version

  pre_build:
    commands:
      - echo "Setting up environment"
      - echo "Maven version:"
      - mvn -v
      - echo "Downloading PEM file from S3"
      - aws s3 cp s3://mobilestore-artifacts/app_jar/mobilestore.pem /tmp/mobilestore.pem
      - chmod 400 /tmp/mobilestore.pem

  build:
    commands:
      - echo "Building the project"
      - mvn clean package
      - echo "Build successful"

  post_build:
    commands:
      - echo "Skipping host key verification for SCP"
      - mkdir -p ~/.ssh
      - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - scp -i /tmp/mobilestore.pem target/mobilestore-0.0.1-SNAPSHOT.jar ec2-user@44.211.74.58:/home/ec2-user/mobilestore-0.0.1-SNAPSHOT.jar
      - echo "Running JAR on EC2"
      - ssh -i /tmp/mobilestore.pem ec2-user@44.211.74.58 'java -jar /home/ec2-user/mobilestore-0.0.1-SNAPSHOT.jar'
      - echo "Deployment successful"

artifacts:
  files:
    - target/*.jar
